version: 3
services:
  exporter:
    build: ./
    ports:
        - 4000:4000
    environment:
      SECRET_KEY_BASE: INSECURE_FOOBAR_2021
      USER_AGENT: "OSRS_GE_EXPORTER @YOUR_DISCORD_HANDLE#1234"
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - "exporter:exporter"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus
